server:
  port: 6004
  servlet:
    context-path: /flowable-server

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace

spring:
  datasource:
    url: jdbc:mysql://192.168.2.110:3306/flowable?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

flowable:
  # 关闭定时任务JOB
  async-executor-activate: false