server:
  port: 6007
  servlet:
    context-path: /common-server

spring:
  servlet:
    multipart:
      # 开启multipart上传功能
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      # 最大文件大小
      max-file-size: 200MB
      # 最大请求大小
      max-request-size: 215MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      # 通过http://localhost:6007/common-server/druid/api.html访问
      # 全局druid参数,绝大部分值和默认保持一致(现已支持的参数如下,不清楚含义不要乱设置)
      druid:
        # 连接池的配置信息
        # 初始化大小: 最小/最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间,单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache,并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能,慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://192.168.2.126:3306/smart-demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: root
          password: 123456
  # Redis配置
  redis:
    host: 192.168.2.126
    port: 7002
    password:
    database: 0
    lettuce:
      pool:
        # 最大连接数据库连接数,设0为没有限制
        max-active: 8
        # 最大等待连接中的数量,设0为没有限制
        max-idle: 8
        # 最大建立连接等待时间,如果超过此时间将接到异常,设为-1表示无限制
        max-wait: -1ms
        # 最小等待连接中的数量,设0为没有限制
        min-idle: 0
      shutdown-timeout: 100ms

# mybatis plus设置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

logging:
  level:
    root: info
