server:
  port: 6002
  servlet:
    context-path: /dubbo-provider

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace

dubbo:
  application:
    name: dubbo-provider #当前服务/应用的名字
  registry: #注册中心的协议和地址
    protocol: zookeeper
    # hw-sonin
    # address: 192.168.8.110:2181
    # jksj
    address: 192.168.2.110:2181
  protocol: #通信规则(通信协议和接口)
    name: dubbo
    port: 20880
  monitor: #连接监控中心
    protocol: registry
