server:
  port: 6003
  servlet:
    context-path: /dubbo-consumer

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace

dubbo:
  application:
    name: dubbo-consumer #当前服务/应用的名字
  registry: #注册中心的协议和地址
    # hw-sonin
    # address: zookeeper://192.168.8.110:2181
    # jksj
    address: zookeeper://192.168.2.110:2181
  monitor: #连接监控中心
    protocol: registry
