server:
  port: 6003
  servlet:
    context-path: /dubbo-consumer

logging:
  config: classpath:logback-spring.xml
  level:
    cn.jay.repository: trace

dubbo:
  application:
    name: dubbo-consumer #当前服务/应用的名字
  registry: #注册中心的协议和地址
    address: zookeeper://192.168.8.110:2181
  monitor: #连接监控中心
    protocol: registry
  scan: #开启包扫描，可替代@EnableDubbo注解
    base-packages: com.sonin.dubboconsumer
